program: main.py
method: grid
parameters:
  gnn_type:
    values: ['originalgin', 'graphconv']
  num_layer:
    values: [6]
  emb_dim:
    values: [32]
  batch_size:
    values: [128]
  learning_rate:
    values: [0.01, 0.001]
  decay_rate:
    value: 0.5
  decay_step:
    value: 50
  epochs:
    value: 350
  dataset:
    values: ['EXP', 'CEXP']
  jk:
    value: 'concat'
  drop_ratio:
    value: 0.
  channels:
    values: ['64-64']
  policy:
    values: ['edge_deletion', 'node_deletion', 'ego', 'ego_plus']
  model:
    values: ['dss']
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
